export const BUFFER_FRAMES = 3;
export const THUMBNAILS_SHEET_WIDTH = 800;
export const THUMBNAIL_WIDTH = 80;
export const THUMBNAIL_FRAMES_MAX_COUNT = 100;
export const THUMBNAIL_FRAMES_PER_AXIS = 10;
